name: build and deploy
on:
  workflow_dispatch:
  push:
    branches: ['disabled']

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # install dependencies
